# insert_songs.py

from flask import current_app
from app import create_app
from extensions import db
from models.song import Song

app = create_app()

songs_data = [
    {"title": "Lose Control", "artist": "Teddy Swims", "album": "Lose Control - Single", "genre": "Pop", "year": 2024, "album_art_url": "https://example.com/lose_control.jpg", "extraversion": 5, "openness": 3, "conscientiousness": 3, "agreeableness": 4, "neuroticism": 2, "energy": 5, "mood": 5, "lyrics_importance": True},
    {"title": "A Bar Song (Tipsy)", "artist": "Shaboozey", "album": "A Bar Song (Tipsy) - Single", "genre": "Country Rap", "year": 2024, "album_art_url": "https://example.com/a_bar_song.jpg", "extraversion": 5, "openness": 2, "conscientiousness": 3, "agreeableness": 3, "neuroticism": 3, "energy": 4, "mood": 4, "lyrics_importance": False},
    {"title": "Beautiful Things", "artist": "Benson Boone", "album": "Beautiful Things - Single", "genre": "Pop", "year": 2024, "album_art_url": "https://example.com/beautiful_things.jpg", "extraversion": 3, "openness": 5, "conscientiousness": 4, "agreeableness": 4, "neuroticism": 2, "energy": 3, "mood": 5, "lyrics_importance": True},
    {"title": "I Had Some Help", "artist": "Post Malone ft. Morgan Wallen", "album": "I Had Some Help - Single", "genre": "Country", "year": 2024, "album_art_url": "https://example.com/i_had_some_help.jpg", "extraversion": 4, "openness": 3, "conscientiousness": 2, "agreeableness": 3, "neuroticism": 3, "energy": 4, "mood": 3, "lyrics_importance": True},
    {"title": "Espresso", "artist": "Sabrina Carpenter", "album": "Espresso - Single", "genre": "Pop", "year": 2024, "album_art_url": "https://example.com/espresso.jpg", "extraversion": 4, "openness": 3, "conscientiousness": 4, "agreeableness": 4, "neuroticism": 2, "energy": 5, "mood": 5, "lyrics_importance": True},
    {"title": "Not Like Us", "artist": "Kendrick Lamar", "album": "Not Like Us - Single", "genre": "Hip-Hop", "year": 2024, "album_art_url": "https://example.com/not_like_us.jpg", "extraversion": 4, "openness": 4, "conscientiousness": 2, "agreeableness": 3, "neuroticism": 3, "energy": 5, "mood": 3, "lyrics_importance": True},
    {"title": "Birds of a Feather", "artist": "Billie Eilish", "album": "Birds of a Feather - Single", "genre": "Alternative", "year": 2024, "album_art_url": "https://example.com/birds_of_a_feather.jpg", "extraversion": 2, "openness": 5, "conscientiousness": 3, "agreeableness": 4, "neuroticism": 4, "energy": 2, "mood": 2, "lyrics_importance": True},
    {"title": "Too Sweet", "artist": "Hozier", "album": "Too Sweet - Single", "genre": "Alternative", "year": 2024, "album_art_url": "https://example.com/too_sweet.jpg", "extraversion": 3, "openness": 5, "conscientiousness": 3, "agreeableness": 4, "neuroticism": 2, "energy": 3, "mood": 4, "lyrics_importance": True},
    {"title": "Please Please Please", "artist": "Sabrina Carpenter", "album": "Please Please Please - Single", "genre": "Pop", "year": 2024, "album_art_url": "https://example.com/please_please_please.jpg", "extraversion": 5, "openness": 3, "conscientiousness": 4, "agreeableness": 4, "neuroticism": 2, "energy": 5, "mood": 5, "lyrics_importance": True},
    {"title": "Cruel Summer", "artist": "Taylor Swift", "album": "Lover", "genre": "Pop", "year": 2019, "album_art_url": "https://example.com/cruel_summer.jpg", "extraversion": 4, "openness": 3, "conscientiousness": 3, "agreeableness": 4, "neuroticism": 2, "energy": 5, "mood": 5, "lyrics_importance": True},
    {"title": "Greedy", "artist": "Tate McRae", "album": "Greedy - Single", "genre": "Pop", "year": 2024, "album_art_url": "https://example.com/greedy.jpg", "extraversion": 4, "openness": 3, "conscientiousness": 4, "agreeableness": 4, "neuroticism": 3, "energy": 5, "mood": 4, "lyrics_importance": True},
    {"title": "Fortnight", "artist": "Taylor Swift ft. Post Malone", "album": "The Tortured Poets Department", "genre": "Pop", "year": 2024, "album_art_url": "https://example.com/fortnight.jpg", "extraversion": 4, "openness": 4, "conscientiousness": 3, "agreeableness": 4, "neuroticism": 3, "energy": 5, "mood": 3, "lyrics_importance": True},
    {"title": "Stick Season", "artist": "Noah Kahan", "album": "Stick Season", "genre": "Folk", "year": 2022, "album_art_url": "https://example.com/stick_season.jpg", "extraversion": 2, "openness": 5, "conscientiousness": 4, "agreeableness": 3, "neuroticism": 5, "energy": 2, "mood": 1, "lyrics_importance": True},
    {"title": "Lovin on Me", "artist": "Jack Harlow", "album": "Lovin on Me - Single", "genre": "Hip-Hop", "year": 2024, "album_art_url": "https://example.com/lovin_on_me.jpg", "extraversion": 5, "openness": 3, "conscientiousness": 2, "agreeableness": 3, "neuroticism": 2, "energy": 5, "mood": 4, "lyrics_importance": False},
    {
    "title": "Dancing in the Dark", 
    "artist": "Bruce Springsteen", 
    "album": "Born in the U.S.A.", 
    "genre": "Rock", 
    "year": 1984, 
    "album_art_url": "https://example.com/dancing_in_the_dark.jpg", 
    "extraversion": 4, 
    "openness": 3, 
    "conscientiousness": 4, 
    "agreeableness": 4, 
    "neuroticism": 2, 
    "energy": 5, 
    "mood": 4, 
    "lyrics_importance": True
}, 
{
    "title": "Blinding Lights", 
    "artist": "The Weeknd", 
    "album": "After Hours", 
    "genre": "Pop", 
    "year": 2020, 
    "album_art_url": "https://example.com/blinding_lights.jpg", 
    "extraversion": 5, 
    "openness": 4, 
    "conscientiousness": 3, 
    "agreeableness": 3, 
    "neuroticism": 3, 
    "energy": 5, 
    "mood": 5, 
    "lyrics_importance": True
}, 
{
    "title": "Take Me To Church", 
    "artist": "Hozier", 
    "album": "Hozier", 
    "genre": "Indie Rock", 
    "year": 2013, 
    "album_art_url": "https://example.com/take_me_to_church.jpg", 
    "extraversion": 3, 
    "openness": 5, 
    "conscientiousness": 4, 
    "agreeableness": 3, 
    "neuroticism": 4, 
    "energy": 3, 
    "mood": 4, 
    "lyrics_importance": True
}, 
{
    "title": "Bad Guy", 
    "artist": "Billie Eilish", 
    "album": "When We All Fall Asleep, Where Do We Go?", 
    "genre": "Pop", 
    "year": 2019, 
    "album_art_url": "https://example.com/bad_guy.jpg", 
    "extraversion": 4, 
    "openness": 5, 
    "conscientiousness": 3, 
    "agreeableness": 3, 
    "neuroticism": 5, 
    "energy": 5, 
    "mood": 3, 
    "lyrics_importance": True
}, 
{
    "title": "Rolling in the Deep", 
    "artist": "Adele", 
    "album": "21", 
    "genre": "Pop", 
    "year": 2010, 
    "album_art_url": "https://example.com/rolling_in_the_deep.jpg", 
    "extraversion": 2, 
    "openness": 3, 
    "conscientiousness": 5, 
    "agreeableness": 4, 
    "neuroticism": 4, 
    "energy": 4, 
    "mood": 3, 
    "lyrics_importance": True
}, 
{
    "title": "Watermelon Sugar", 
    "artist": "Harry Styles", 
    "album": "Fine Line", 
    "genre": "Pop", 
    "year": 2019, 
    "album_art_url": "https://example.com/watermelon_sugar.jpg", 
    "extraversion": 5, 
    "openness": 4, 
    "conscientiousness": 3, 
    "agreeableness": 4, 
    "neuroticism": 2, 
    "energy": 5, 
    "mood": 5, 
    "lyrics_importance": True
}, 
{
    "title": "Shape of You", 
    "artist": "Ed Sheeran", 
    "album": "÷", 
    "genre": "Pop", 
    "year": 2017, 
    "album_art_url": "https://example.com/shape_of_you.jpg", 
    "extraversion": 5, 
    "openness": 4, 
    "conscientiousness": 3, 
    "agreeableness": 4, 
    "neuroticism": 3, 
    "energy": 5, 
    "mood": 4, 
    "lyrics_importance": True
}, 
{
    "title": "Viva La Vida", 
    "artist": "Coldplay", 
    "album": "Viva La Vida or Death and All His Friends", 
    "genre": "Rock", 
    "year": 2008, 
    "album_art_url": "https://example.com/viva_la_vida.jpg", 
    "extraversion": 3, 
    "openness": 4, 
    "conscientiousness": 4, 
    "agreeableness": 5, 
    "neuroticism": 3, 
    "energy": 4, 
    "mood": 5, 
    "lyrics_importance": True
}, 
{
    "title": "Happier", 
    "artist": "Marshmello ft. Bastille", 
    "album": "Happier - Single", 
    "genre": "Pop", 
    "year": 2018, 
    "album_art_url": "https://example.com/happier.jpg", 
    "extraversion": 4, 
    "openness": 3, 
    "conscientiousness": 4, 
    "agreeableness": 5, 
    "neuroticism": 3, 
    "energy": 4, 
    "mood": 5, 
    "lyrics_importance": True
}, 
{
    "title": "Old Town Road", 
    "artist": "Lil Nas X", 
    "album": "7", 
    "genre": "Hip-Hop", 
    "year": 2019, 
    "album_art_url": "https://example.com/old_town_road.jpg", 
    "extraversion": 5, 
    "openness": 2, 
    "conscientiousness": 3, 
    "agreeableness": 3, 
    "neuroticism": 4, 
    "energy": 5, 
    "mood": 4, 
    "lyrics_importance": True
}, 
{
    "title": "Counting Stars", 
    "artist": "OneRepublic", 
    "album": "Native", 
    "genre": "Pop Rock", 
    "year": 2013, 
    "album_art_url": "https://example.com/counting_stars.jpg", 
    "extraversion": 5, 
    "openness": 3, 
    "conscientiousness": 4, 
    "agreeableness": 4, 
    "neuroticism": 3, 
    "energy": 5, 
    "mood": 5, 
    "lyrics_importance": True
}, 
{
    "title": "Let It Be", 
    "artist": "The Beatles", 
    "album": "Let It Be", 
    "genre": "Rock", 
    "year": 1970, 
    "album_art_url": "https://example.com/let_it_be.jpg", 
    "extraversion": 3, 
    "openness": 5, 
    "conscientiousness": 5, 
    "agreeableness": 4, 
    "neuroticism": 2, 
    "energy": 3, 
    "mood": 3, 
    "lyrics_importance": True
}, 
{
    "title": "Smells Like Teen Spirit", 
    "artist": "Nirvana", 
    "album": "Nevermind", 
    "genre": "Grunge", 
    "year": 1991, 
    "album_art_url": "https://example.com/smells_like_teen_spirit.jpg", 
    "extraversion": 4, 
    "openness": 4, 
    "conscientiousness": 3, 
    "agreeableness": 3, 
    "neuroticism": 4, 
    "energy": 5, 
    "mood": 3, 
    "lyrics_importance": True
}, 
{
    "title": "Lose Yourself", 
    "artist": "Eminem", 
    "album": "8 Mile Soundtrack", 
    "genre": "Hip-Hop", 
    "year": 2002, 
    "album_art_url": "https://example.com/lose_yourself.jpg", 
    "extraversion": 5, 
    "openness": 3, 
    "conscientiousness": 4, 
    "agreeableness": 3, 
    "neuroticism": 5, 
    "energy": 5, 
    "mood": 5, 
    "lyrics_importance": True
}

]

with app.app_context():
    for s in songs_data:
        song = Song(
            title=s["title"],
            artist=s["artist"],
            album=s["album"],
            genre=s["genre"],
            year=s["year"],
            album_art_url=s["album_art_url"],
            extraversion=s["extraversion"],
            openness=s["openness"],
            conscientiousness=s["conscientiousness"],
            agreeableness=s["agreeableness"],
            neuroticism=s["neuroticism"],
            energy=s["energy"],
            mood=s["mood"],
            lyrics_importance=s["lyrics_importance"]
        )
        db.session.add(song)
    db.session.commit()
    print("Inserted", len(songs_data), "songs!")
