"""Initial migration

Revision ID: ff45ec61733d
Revises: 
Create Date: 2025-05-05 11:10:35.616822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff45ec61733d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('preferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genre_preference', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('mood', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('preferences', schema=None) as batch_op:
        batch_op.drop_column('mood')
        batch_op.drop_column('genre_preference')

    # ### end Alembic commands ###
